function [] = plotFlux(data1, data2, ax)
    plot(data1.h_init(data1.xy(data1.dwnSt_bound,1),data1.xy(data1.dwnSt_bound,2))...
        .*sqrt(data1.u(data1.dwnSt_bound).^2+data1.v(data1.dwnSt_bound).^2)*3.154E7...
        ,'k')
    hold on
    plot(data2.h_init(data1.xy(data1.dwnSt_bound,1),data1.xy(data1.dwnSt_bound,2))...
        .*sqrt(data2.u(data1.dwnSt_bound).^2+data2.v(data1.dwnSt_bound).^2)*3.154E7...
        ,'--','color',rgb('gray'),'linewidth',2)
    
    plot(data1.h_init(data1.xy(data1.upSt_bound,1),data1.xy(data1.upSt_bound,2))...
        .*sqrt(data1.u(data1.upSt_bound).^2+data1.v(data1.upSt_bound).^2)*3.154E7...
        ,'k')
    plot(data2.h_init(data1.xy(data1.upSt_bound,1),data1.xy(data1.upSt_bound,2))...
        .*sqrt(data2.u(data1.upSt_bound).^2+data2.v(data1.upSt_bound).^2)*3.154E7...
        ,'--','color',rgb('gray'),'linewidth',2)
    
end